services:
  mongo:
    image: mongo:7
    command: ["--replSet", "rs0", "--bind_ip_all"]
    ports: ["27017:27017"]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 5s
      timeout: 3s
      retries: 10
    volumes:
      - mongo_data:/data/db

  rs-init:
    image: mongo:7
    depends_on:
      mongo:
        condition: service_healthy
    entrypoint: ["bash", "-lc", "mongosh --host mongo --eval \"try{rs.initiate({_id:'rs0',members:[{_id:0,host:'mongo:27017'}]})}catch(e){print(e)}; while(rs.status().members[0].stateStr!='PRIMARY') { sleep(1) }\""]

volumes:
  mongo_data: {}