name: ci
on:
  push:
    branches: [ main ]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongodb/mongodb-community-server:7.0-ubi8
        ports: ['27017:27017']
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json
          run_install: false
      - uses: actions/setup-node@v4
        with: { node-version: '20', cache: 'pnpm' }
      - run: pnpm install
      - run: echo "DATABASE_URL=mongodb://localhost:27017/insightfc" >> .env
      - run: pnpm build
      - run: pnpm test
      - name: Start API
        run: pnpm --filter api dev & sleep 5
      - name: Run BDD
        run: API_BASE_URL=http://localhost:3000 pnpm bdd